### ISSUE TITLE
FETCH COMMAND ERROR

### ISSUE THREAD

**Issue by lampda** [awangga/outlook#5]
I am using this module in my Mac os, with Python 2.7, but while trying to read emails I got the error, 
**FETCH command error: BAD ['The specified message set is invalid.']**

Can you help and fix this?

**Comment by fairsky66** [comment]
I doubt this error was raised due to the multipart type of my email which contains images/attachments.
So my request is: Is there any way to handle multipart messages or just ignore images/attachments?

**Comment by awangga** [comment]
please consider pull request, i hope you enjoy this library
