### ISSUE TITLE
Outlook instance has no attribute 'imap'

### ISSUE THREAD

**Issue by LakshmiRamya-G** [awangga/outlook#6]
After downloading the python script files, I created a separate python file with the code "To get latest Unread Message in inbox" from Readme.md. Whenever I run this file, I get the ERROR- "Outlook instance has no attribute 'imap' ".

**Comment by qig-smiller** [comment]
I am experiencing this issue also

**Comment by qig-smiller** [comment]
I think this issue arises from the fact that **the _self.imap_ variable wasn't declared in the _init_ method**.

simply moving this declaration to init should solve the issue

i am unable to test this as I am having other login issues not relating to this variable.

**Comment by awangga** [comment]
this issues has fixed
